// Mocks generated by Mockito 5.4.6 from annotations
// in playground/test/service/base_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:convert' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:playground/service/base_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseService extends _i1.Mock implements _i2.BaseService {
  MockBaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get commonApiUrl => (super.noSuchMethod(
        Invocation.getter(#commonApiUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#commonApiUrl),
        ),
      ) as String);

  @override
  _i4.Future<Map<String, dynamic>> get<T extends _i2.JsonSerializer>(
    String? url, {
    Map<String, String>? headers,
    Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {
            #headers: headers,
            #params: params,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> post<T extends _i2.JsonSerializer>(
    String? url, {
    Map<String, String>? headers,
    Map<String, dynamic>? params,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #params: params,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> put<T extends _i2.JsonSerializer>(
    String? url, {
    Map<String, String>? headers,
    Map<String, dynamic>? params,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #params: params,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> delete<T extends _i2.JsonSerializer>(
    String? url, {
    Map<String, String>? headers,
    Map<String, dynamic>? params,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #params: params,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>>
      multipartRequest<T extends _i2.JsonSerializer>(
    String? url, {
    required List<_i2.MultiPartFileData>? files,
    Map<String, String>? headers,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #multipartRequest,
              [url],
              {
                #files: files,
                #headers: headers,
              },
            ),
            returnValue:
                _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
          ) as _i4.Future<Map<String, dynamic>>);
}
